export { FeedbackPressProvider, type FeedbackPressProviderProps } from './FeedbackPressProvider'
export type { HapticSettings } from './HapticSettingsContext'
export { defaultHapticSettings, HapticSettingsContext } from './HapticSettingsContext'
export { type PaperModuleShape, useFeedbackPressPaper } from './PaperContext'
export { hapticActions, hapticReducer } from './redux/hapticSlice'
export { type SoundConfig, SoundContext } from './SoundContext'
export { type FeedbackTrigger, type FeedbackWiring, type FeedbackWiringEntry, PRESS_WIRING, useFeedbackHandlers } from './useFeedbackHandlers'
export { useHapticSettings } from './useHapticSettings'
export { useVibration } from './useVibration'
export { withFeedback } from './withFeedback'

// Native wrappers
export { Pressable, type PressableProps } from './components/native/Pressable'
export { TouchableHighlight, type TouchableHighlightProps } from './components/native/TouchableHighlight'
export { TouchableOpacity, type TouchableOpacityProps } from './components/native/TouchableOpacity'

// Paper wrappers (requires react-native-paper peer dep)
export { AppbarAction, type AppbarActionProps } from './components/paper/AppbarAction'
export { AppbarBackAction, type AppbarBackActionProps } from './components/paper/AppbarBackAction'
export { Button, type ButtonProps } from './components/paper/Button'
export { Card, type CardProps } from './components/paper/Card'
export { Checkbox, type CheckboxProps } from './components/paper/Checkbox'
export { Chip, type ChipProps } from './components/paper/Chip'
export { FAB, type FABProps } from './components/paper/FAB'
export { IconButton, type IconButtonProps } from './components/paper/IconButton'
export { SegmentedButtons, type SegmentedButtonsProps } from './components/paper/SegmentedButtons'
export { Switch, type SwitchProps } from './components/paper/Switch'
export { TouchableRipple, type TouchableRippleProps } from './components/paper/TouchableRipple'
